//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorBot.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServidorBot.Resources.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        public static string CREATE_EMBED_AUTHOR_NAME {
            get {
                return ResourceManager.GetString("CREATE_EMBED_AUTHOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL:.
        /// </summary>
        public static string CREATE_EMBED_AUTHOR_URL {
            get {
                return ResourceManager.GetString("CREATE_EMBED_AUTHOR_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL Icon:.
        /// </summary>
        public static string CREATE_EMBED_AUTHOR_URL_ICON {
            get {
                return ResourceManager.GetString("CREATE_EMBED_AUTHOR_URL_ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color:.
        /// </summary>
        public static string CREATE_EMBED_COLOR {
            get {
                return ResourceManager.GetString("CREATE_EMBED_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description:.
        /// </summary>
        public static string CREATE_EMBED_DESCRIPTION {
            get {
                return ResourceManager.GetString("CREATE_EMBED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Field.
        /// </summary>
        public static string CREATE_EMBED_FIELD_ADD {
            get {
                return ResourceManager.GetString("CREATE_EMBED_FIELD_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inline:.
        /// </summary>
        public static string CREATE_EMBED_FIELD_INLINE {
            get {
                return ResourceManager.GetString("CREATE_EMBED_FIELD_INLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        public static string CREATE_EMBED_FIELD_NAME {
            get {
                return ResourceManager.GetString("CREATE_EMBED_FIELD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Field.
        /// </summary>
        public static string CREATE_EMBED_FIELD_REMOVE {
            get {
                return ResourceManager.GetString("CREATE_EMBED_FIELD_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value:.
        /// </summary>
        public static string CREATE_EMBED_FIELD_VALUE {
            get {
                return ResourceManager.GetString("CREATE_EMBED_FIELD_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text Footer:.
        /// </summary>
        public static string CREATE_EMBED_FOOTER_TEXT {
            get {
                return ResourceManager.GetString("CREATE_EMBED_FOOTER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL Text Footer:.
        /// </summary>
        public static string CREATE_EMBED_FOOTER_TEXT_URL {
            get {
                return ResourceManager.GetString("CREATE_EMBED_FOOTER_TEXT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image URL:.
        /// </summary>
        public static string CREATE_EMBED_IMAGE_URL {
            get {
                return ResourceManager.GetString("CREATE_EMBED_IMAGE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must complete in German: \n-Author\n-Title\n-Description\n-Footer\n-or add a Field..
        /// </summary>
        public static string CREATE_EMBED_MENSAJE_ERROR_EMBED {
            get {
                return ResourceManager.GetString("CREATE_EMBED_MENSAJE_ERROR_EMBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must fill in the fields both the name and the value..
        /// </summary>
        public static string CREATE_EMBED_MENSAJE_ERROR_FIELD {
            get {
                return ResourceManager.GetString("CREATE_EMBED_MENSAJE_ERROR_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thumbnail URL:.
        /// </summary>
        public static string CREATE_EMBED_THUMBNAIL_URL {
            get {
                return ResourceManager.GetString("CREATE_EMBED_THUMBNAIL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time Stamp:.
        /// </summary>
        public static string CREATE_EMBED_TIMESTAMP {
            get {
                return ResourceManager.GetString("CREATE_EMBED_TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title:.
        /// </summary>
        public static string CREATE_EMBED_TITLE {
            get {
                return ResourceManager.GetString("CREATE_EMBED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL:.
        /// </summary>
        public static string CREATE_EMBED_TITLE_URL {
            get {
                return ResourceManager.GetString("CREATE_EMBED_TITLE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Embed.
        /// </summary>
        public static string CREATE_EMBED_TITLE_WINDOWS {
            get {
                return ResourceManager.GetString("CREATE_EMBED_TITLE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time active:.
        /// </summary>
        public static string CREATE_EVENT_DATE_TIME_ACTIVE {
            get {
                return ResourceManager.GetString("CREATE_EVENT_DATE_TIME_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hour utc?.
        /// </summary>
        public static string CREATE_EVENT_HOUR_UTC {
            get {
                return ResourceManager.GetString("CREATE_EVENT_HOUR_UTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name event:.
        /// </summary>
        public static string CREATE_EVENT_NAME_EVENT {
            get {
                return ResourceManager.GetString("CREATE_EVENT_NAME_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time repeat:.
        /// </summary>
        public static string CREATE_EVENT_TIME_REPEAT {
            get {
                return ResourceManager.GetString("CREATE_EVENT_TIME_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Event.
        /// </summary>
        public static string CREATE_EVENT_TITLE {
            get {
                return ResourceManager.GetString("CREATE_EVENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string MAIN_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("MAIN_WINDOW_TITLE", resourceCulture);
            }
        }
    }
}
